# Generated by Django 5.2.5 on 2025-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown Title', max_length=200)),
                ('author', models.CharField(default='Unknown Author', max_length=100)),
                ('publication_year', models.IntegerField(default=1900)),
            ],
        ),
    ]
